json.extract! location,             
  :id,
  :location_name,
  :location_description,
  :location_phone,
  :location_email,
  :location_website_url,
  :location_address,
  :location_street_number,
  :location_street_name,
  :location_street_suffix,
  :location_city,
  :location_state_abbreviation,
  :location_postal_code,
  :location_country_code,
  :location_latitude,
  :location_longitude,
  :location_available